{
 "title": "All Servers Overview",
 "description": "Creating a comprehensive dashboard that amalgamates the vital statistics of multiple servers, encompassing CPU utilization, RAM allocation, disk capacity, and various other metrics. This intricate instrumentation leverages exporters and establishes seamless connectivity with a PostgreSQL backend. This meticulously crafted dashboard finds its purpose in overseeing the health and performance of our web servers.",
 "time": { "from": "now-15m", "to": "now-5s" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "All servers stats",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{instance=~\".*:61100\"} != 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Resource Overview",
   "type": "table",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 14, "w": 22, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_uname_info{} - 0", "legendFormat": "主机名" },
    {
     "expr": "sum(time() - node_boot_time_seconds{})by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode='system'}) by (instance)",
     "legendFormat": "总核数"
    },
    { "expr": "node_load5{}", "legendFormat": "5分钟负载" },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{} / (node_memory_MemTotal_bytes{})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{}[5m])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{}[5m])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{} - 0",
     "legendFormat": "连接数"
    },
    { "expr": "node_sockstat_TCP_tw{} - 0", "legendFormat": "TIME_WAIT" },
    {
     "expr": "max(rate(node_network_receive_bytes_total{}[5m])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{}[5m])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_timex_sync_status{instance=~\".*:61100\"})"
    }
   ]
  },
  {
   "title": "DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{instance=~\".*:61100\"}) - count(node_timex_sync_status{instance=~\".*:61100\"})"
    }
   ]
  },
  {
   "title": "TOTAL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{instance=~\".*:61100\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 22, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (job, instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 22, "x": 2, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (avg by (job, instance) (node_memory_MemAvailable_bytes) / avg by (job, instance) (node_memory_MemTotal_bytes)))\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 22, "x": 2, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (avg by (job, instance) (node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay\"}) / avg by (job, instance) (node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"})))\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "up{instance=~\".*:61100\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "up{instance=~\".*:61100\"} != 1",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}