{
 "title": "Waku Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values({job=\"$server\", instance=~\".*:8003\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes Total",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "libp2p_peers{instance=~\".*:8003\"} == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Nodes Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 22, "x": 2, "y": 0 },
   "targets": [
    { "expr": "libp2p_peers", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libp2p_peers{instance=~\".*:8003\"} != 0)",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libp2p_peers{instance=~\".*:8003\"} == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libp2p_peers{instance=~\".*:8003\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Node Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waku_version{instance=\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Node Connected Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_peers{instance=\"${node}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "All Nodes Versions",
   "type": "stat",
   "gridPos": { "h": 11, "w": 22, "x": 2, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "waku_version", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waku_connected_peers{instance=~\".*:8003\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Down",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "libp2p_peers == 0", "legendFormat": "__auto" }
   ]
  }
 ]
}